/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedServicesIndexRouteImport } from './routes/_authenticated/services/index'
import { Route as AuthenticatedEmployeesIndexRouteImport } from './routes/_authenticated/employees/index'
import { Route as AuthenticatedSettingsBusinessDetailsRouteImport } from './routes/_authenticated/settings/business-details'
import { Route as AuthenticatedServicesCategoriesRouteImport } from './routes/_authenticated/services/categories'
import { Route as AuthenticatedEmployeesPositionsRouteImport } from './routes/_authenticated/employees/positions'
import { ServerRoute as ApiMediaIndexServerRouteImport } from './routes/api/media/index'
import { ServerRoute as ApiBookingIndexServerRouteImport } from './routes/api/booking/index'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const rootServerRouteImport = createServerRootRoute()

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedServicesIndexRoute =
  AuthenticatedServicesIndexRouteImport.update({
    id: '/services/',
    path: '/services/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmployeesIndexRoute =
  AuthenticatedEmployeesIndexRouteImport.update({
    id: '/employees/',
    path: '/employees/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsBusinessDetailsRoute =
  AuthenticatedSettingsBusinessDetailsRouteImport.update({
    id: '/settings/business-details',
    path: '/settings/business-details',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedServicesCategoriesRoute =
  AuthenticatedServicesCategoriesRouteImport.update({
    id: '/services/categories',
    path: '/services/categories',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmployeesPositionsRoute =
  AuthenticatedEmployeesPositionsRouteImport.update({
    id: '/employees/positions',
    path: '/employees/positions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiMediaIndexServerRoute = ApiMediaIndexServerRouteImport.update({
  id: '/api/media/',
  path: '/api/media/',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiBookingIndexServerRoute = ApiBookingIndexServerRouteImport.update({
  id: '/api/booking/',
  path: '/api/booking/',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/sign-up': typeof SignUpRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employees/positions': typeof AuthenticatedEmployeesPositionsRoute
  '/services/categories': typeof AuthenticatedServicesCategoriesRoute
  '/settings/business-details': typeof AuthenticatedSettingsBusinessDetailsRoute
  '/employees': typeof AuthenticatedEmployeesIndexRoute
  '/services': typeof AuthenticatedServicesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/sign-up': typeof SignUpRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employees/positions': typeof AuthenticatedEmployeesPositionsRoute
  '/services/categories': typeof AuthenticatedServicesCategoriesRoute
  '/settings/business-details': typeof AuthenticatedSettingsBusinessDetailsRoute
  '/employees': typeof AuthenticatedEmployeesIndexRoute
  '/services': typeof AuthenticatedServicesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/sign-up': typeof SignUpRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/employees/positions': typeof AuthenticatedEmployeesPositionsRoute
  '/_authenticated/services/categories': typeof AuthenticatedServicesCategoriesRoute
  '/_authenticated/settings/business-details': typeof AuthenticatedSettingsBusinessDetailsRoute
  '/_authenticated/employees/': typeof AuthenticatedEmployeesIndexRoute
  '/_authenticated/services/': typeof AuthenticatedServicesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/features'
    | '/login'
    | '/pricing'
    | '/sign-up'
    | '/calendar'
    | '/dashboard'
    | '/employees/positions'
    | '/services/categories'
    | '/settings/business-details'
    | '/employees'
    | '/services'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/features'
    | '/login'
    | '/pricing'
    | '/sign-up'
    | '/calendar'
    | '/dashboard'
    | '/employees/positions'
    | '/services/categories'
    | '/settings/business-details'
    | '/employees'
    | '/services'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/features'
    | '/login'
    | '/pricing'
    | '/sign-up'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/employees/positions'
    | '/_authenticated/services/categories'
    | '/_authenticated/settings/business-details'
    | '/_authenticated/employees/'
    | '/_authenticated/services/'
    | '/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SignUpRoute: typeof SignUpRoute
}
export interface FileServerRoutesByFullPath {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/booking': typeof ApiBookingIndexServerRoute
  '/api/media': typeof ApiMediaIndexServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/booking': typeof ApiBookingIndexServerRoute
  '/api/media': typeof ApiMediaIndexServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/booking/': typeof ApiBookingIndexServerRoute
  '/api/media/': typeof ApiMediaIndexServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/auth/$' | '/api/booking' | '/api/media'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/auth/$' | '/api/booking' | '/api/media'
  id: '__root__' | '/api/auth/$' | '/api/booking/' | '/api/media/'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
  ApiBookingIndexServerRoute: typeof ApiBookingIndexServerRoute
  ApiMediaIndexServerRoute: typeof ApiMediaIndexServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/services/': {
      id: '/_authenticated/services/'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/employees/': {
      id: '/_authenticated/employees/'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/business-details': {
      id: '/_authenticated/settings/business-details'
      path: '/settings/business-details'
      fullPath: '/settings/business-details'
      preLoaderRoute: typeof AuthenticatedSettingsBusinessDetailsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/services/categories': {
      id: '/_authenticated/services/categories'
      path: '/services/categories'
      fullPath: '/services/categories'
      preLoaderRoute: typeof AuthenticatedServicesCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/employees/positions': {
      id: '/_authenticated/employees/positions'
      path: '/employees/positions'
      fullPath: '/employees/positions'
      preLoaderRoute: typeof AuthenticatedEmployeesPositionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/media/': {
      id: '/api/media/'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaIndexServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/booking/': {
      id: '/api/booking/'
      path: '/api/booking'
      fullPath: '/api/booking'
      preLoaderRoute: typeof ApiBookingIndexServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmployeesPositionsRoute: typeof AuthenticatedEmployeesPositionsRoute
  AuthenticatedServicesCategoriesRoute: typeof AuthenticatedServicesCategoriesRoute
  AuthenticatedSettingsBusinessDetailsRoute: typeof AuthenticatedSettingsBusinessDetailsRoute
  AuthenticatedEmployeesIndexRoute: typeof AuthenticatedEmployeesIndexRoute
  AuthenticatedServicesIndexRoute: typeof AuthenticatedServicesIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmployeesPositionsRoute: AuthenticatedEmployeesPositionsRoute,
  AuthenticatedServicesCategoriesRoute: AuthenticatedServicesCategoriesRoute,
  AuthenticatedSettingsBusinessDetailsRoute:
    AuthenticatedSettingsBusinessDetailsRoute,
  AuthenticatedEmployeesIndexRoute: AuthenticatedEmployeesIndexRoute,
  AuthenticatedServicesIndexRoute: AuthenticatedServicesIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
  ApiBookingIndexServerRoute: ApiBookingIndexServerRoute,
  ApiMediaIndexServerRoute: ApiMediaIndexServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
